name: notes
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_svg: ^2.0.11
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  modal_progress_hud_nsn: ^0.5.1

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/playstore.png"
  min_sdk_android: 24
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/playstore.png"

flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Sofia Sans
      fonts:
        - asset: assets/fonts/static/SofiaSans-Regular.ttf
        - asset: assets/fonts/static/SofiaSans-ExtraBold.ttf
        - asset: assets/fonts/static/SofiaSans-Medium.ttf
